version: '3'

tasks:
  default:
    cmds:
      - task --list

  dev:
    desc: Start Hugo dev server
    cmds:
      - hugo server -D --port 8000

  build:
    desc: Build for production
    cmds:
      - hugo --minify

  clean:
    aliases: [reset]
    desc: GC Hugo cache and remove build artifacts
    cmds:
      - hugo --gc
      - rm -rf public resources .hugo_build.lock
